import { NextResponse } from "next/server";
import crypto from "node:crypto";
import { z } from "zod";
import { getDb } from "../../../../lib/db";
import { env } from "../../../../lib/env";
import { hashPassword } from "../../../../lib/auth";
import { sendVerificationEmail } from "../../../../lib/email"; import { encrypt } from "../../../../lib/crypto";
const schema=z.object({
 firstName:z.string().min(2),lastName:z.string().min(2),email:z.string().email(),phone:z.string().min(9),alternatePhone:z.string().optional(),dateOfBirth:z.string().optional(),nationality:z.string().min(2),idType:z.enum(["national_id","passport","alien_card","other"]),idNumber:z.string().min(3),gender:z.string().optional(),address:z.string().min(3),county:z.string().min(2),town:z.string().min(2),postalCode:z.string().optional(),occupation:z.string().min(2),organization:z.string().optional(),memberType:z.enum(["individual","professional","corporate"]).default("individual"),password:z.string().min(env.PASSWORD_MIN_LENGTH),
});
export async function POST(req:Request){try{const body=schema.parse(await req.json());const db=await getDb();const email=body.email.toLowerCase();if(await db.collection("users").findOne({email}))return NextResponse.json({error:"Email already registered"},{status:409});const token=crypto.randomBytes(48).toString("hex");const user={...body,idNumber:encrypt(body.idNumber),email,passwordHash:await hashPassword(body.password),role:"member",status:"pending_email_verification",emailVerified:false,emailVerificationTokenHash:crypto.createHash("sha256").update(token).digest("hex"),emailVerificationExpiresAt:new Date(Date.now()+env.EMAIL_VERIFICATION_EXPIRES_HOURS*3600000),createdAt:new Date(),updatedAt:new Date()};delete (user as any).password;const result=await db.collection("users").insertOne(user);await sendVerificationEmail(email,`${body.firstName} ${body.lastName}`,token);await db.collection("audit_logs").insertOne({action:"USER_REGISTERED",userId:result.insertedId,createdAt:new Date()});return NextResponse.json({ok:true,userId:String(result.insertedId),message:"Registration successful. Check your email to verify your account."},{status:201})}catch(e:any){return NextResponse.json({error:e?.message||"Invalid registration"},{status:400})}}
